// packages/website/src/components/Card/ErrorCard.svelte
<style lang="scss">
  button {
    font-size: 0.875em;
  }

  [role='heading'] {
    font-size: 1.25rem;
  }

  .svg-container {
    margin-right: var(--space-l);
    height: var(--space-l);
    width: var(--space-l);
  }

  .content-container {
    flex: 1;
  }

  .more-container {
    margin-top: var(--space-l);
    text-align: right;

    .svg-container {
      margin-right: var(--space-s);
    }
  }
</style>

<script lang="ts">
  import { _ } from 'svelte-i18n';

  import AlertIcon from 'assets/icons/alert.svg';
  import MoreIcon from 'assets/icons/more.svg';
  import Card from 'components/Card/Card.svelte';

  export let error: string;
  export let message: string;

  let show = false;

  const toggleShow = (e: MouseEvent) => {
    e.preventDefault();
    show = !show;
  };
</script>

<Card variant="grey">
  <div class="svg-container">
    {@html AlertIcon}
  </div>
  <div class="content-container">
    <span role="heading" aria-level="2">{message}</span>
    {#if error}
      <div class="more-container">
        {#if !show}
          <button on:click="{toggleShow}"><div class="svg-container">
              {@html MoreIcon}
            </div>{$_('actions.showMore')}
          </button>
        {:else}<code>{error}</code>{/if}
      </div>
    {/if}
  </div>
</Card>

// packages/website/components/Card/ErrorCard.tsx
import { useState } from 'preact/hooks';
import { useText } from 'preact-i18n';

import Card from 'components/Card/Card';
import AlertIcon from 'assets/icons/alert.svg';
import MoreIcon from 'assets/icons/more.svg';

import styles from 'components/Card/ErrorCard.module.css';

const ErrorCard = ({
  message,
  stack,
}: {
  message: string;
  stack?: string;
}): JSX.Element => {
  const [stackShown, setStackShown] = useState(false);
  const { error, showStack } = useText({
    error: 'error.title',
    showStack: 'error.showStack',
  });

  const toggleStack = (event): void => {
    event.preventDefault();
    return setStackShown(true);
  };

  return (
    <Card variant="secondary" className={styles.error}>
      <AlertIcon role="image" aria-hidden />
      <div className={styles.container}>
        <span role="heading" aria-level={2}>
          {error}
        </span>
        <span>{message}</span>
        {stackShown && <small>{stack}</small>}
      </div>
      {stack && !stackShown && (
        <button className={styles.button} onClick={toggleStack}>
          <MoreIcon aria-label={showStack} />
        </button>
      )}
    </Card>
  );
};

export default ErrorCard;
