// packages/website/src/components/Card/TemperatureCard.svelte
<style lang="scss">
  a {
    transition: opacity 200ms ease-in;
    flex: 0 0 auto;
    display: block;
    border-radius: 9999px;
    padding: var(--space-s);
    color: HSL(var(--bg));
    background-color: HSL(var(--fg));
    height: var(--size-touch);
    width: var(--size-touch);
    opacity: 0.667;

    @media (hover: none) {
      opacity: 1;
    }

    &:focus {
      outline: none;
    }

    &:focus,
    &:hover {
      opacity: 1;
    }
  }
  .container {
    flex: 1;
    padding: var(--space-m);
  }

  .header,
  .footer {
    flex: 1 0 auto;
    width: 100%;
  }

  .header {
    display: flex;
    align-items: flex-end;
    align-self: start;
    justify-content: space-between;
    border-bottom: 1px solid HSL(var(--color-main), 0.25);
    margin-bottom: var(--space-m);
    text-transform: uppercase;
  }

  .header,
  .footer,
  .label {
    letter-spacing: var(--letter-spacing);
  }

  .footer,
  .data,
  .label {
    text-align: right;
  }

  .data,
  .label {
    display: block;
    width: 100%;
  }

  .data {
    font-size: 2.5rem;
  }

  .footer,
  .label {
    opacity: 0.875;
  }

  .footer {
    align-self: end;

    span {
      display: inline-block;
      height: 1em;
    }
  }
</style>

<script lang="ts">
  import { _, date, number, time } from 'svelte-i18n';
  import type { EntrySchema } from '@saschazar/weather-app-functions/db/schemata/entry';
  import type { StationSchema } from '@saschazar/weather-app-functions/db/schemata/station';

  import AlertIcon from 'assets/icons/alert.svg';
  import ArrowUpRighticon from 'assets/icons/arrow-up-right.svg';
  import Card from 'components/Card/Card.svelte';
  import { DAY } from 'utils/constants';

  export let segment: string;

  export let variant: 'grey' | 'primary' | 'secondary';

  export let data: EntrySchema;

  const {
    timestamp,
    temperature,
    temperature2,
    humidity,
    feels,
    station,
  } = data;

  const {
    name,
    id,
    config: {
      temperature: temperatureConfig,
      temperature2: temperature2Config,
    },
  } = station as StationSchema;
</script>

<Card variant="{variant}">
  {#if name}
    <div class="container header">
      <span
        role="heading"
        aria-level="2"
        aria-label="{$_('station.latestEntry')}: {name}"
      >
        <strong>{name}</strong>
      </span>
      {#if id && segment !== id}
        <a rel="prefetch" href="/stations/{id}">{@html ArrowUpRighticon}</a>
      {/if}
    </div>
  {/if}
  {#if temperature}
    <div class="container">
      <small class="label">{$_(`config.${temperatureConfig}`)}:</small><span
        class="data"
      >{$number(temperature, { format: 'compactShort' })}<sup>°C</sup></span>
    </div>
  {/if}
  {#if temperature2}
    <div class="container">
      <small class="label">{$_(`config.${temperature2Config}`)}:</small><span
        class="data"
      >{$number(temperature2, { format: 'compactShort' })}<sup>°C</sup></span>
    </div>
    <div class="container">
      <small class="label">{$_('feels')}:</small><span
        class="data"
      >{$number(feels, { format: 'compactShort' })}<sup>°C</sup></span>
    </div>
    <div class="container">
      <small class="label">{$_('humidity')}:</small><span
        class="data"
      >{$number(humidity, { format: 'compactShort' })}<sup>%</sup></span>
    </div>
  {/if}
  {#if timestamp}
    <small class="container footer">
      {$_('station.lastUpdated')}:
      {#if new Date(timestamp).valueOf() < Date.now() - DAY}
        <span>{@html AlertIcon}</span>
        {$date(new Date(timestamp), { format: 'medium' })}
      {/if}
      {$time(new Date(timestamp), { format: 'short' })}
    </small>
  {/if}
</Card>

// packages/website/components/Card/TemperatureCard.tsx
import classnames from 'classnames';
import dynamic from 'next/dynamic';
import Link from 'next/link';
import { useRouter } from 'next/router';
import { useText, Text } from 'preact-i18n';
import type { EntrySchema } from 'functions/dist/db/schemata/entry';
import type { StationSchema } from 'functions/dist/db/schemata/station';

import AlertIcon from 'assets/icons/alert.svg';
import ArrowUpRightIcon from 'assets/icons/arrow-up-right.svg';
import Card from 'components/Card/Card';
import { DAY } from 'utils/constants';
import useLocale from 'utils/hooks/useLocale';

import styles from 'components/Card/TemperatureCard.module.scss';

export interface EntryProps extends EntrySchema {
  station: StationSchema;
}
export interface TemperatureCardProps {
  entry: EntryProps;
  link?: boolean;
  loading?: boolean;
  variant: 'grey' | 'primary' | 'secondary';
}

const TemperatureCard = ({
  link,
  loading,
  variant,
  entry: {
    timestamp,
    temperature,
    temperature2,
    humidity,
    feels,
    station: {
      id,
      name,
      config: {
        temperature: temperatureConfig,
        temperature2: temperature2Config,
      },
    },
  },
}: TemperatureCardProps): JSX.Element => {
  const { locale } = useRouter();
  const dayjs = useLocale(locale);
  const {
    feelsI18n,
    humidityI18n,
    lastUpdated,
    latestEntry,
    loadingLabel,
    temp,
    temp2,
    tempConfig,
    temp2Config,
  } = useText({
    feelsI18n: 'temperature.feels',
    humidityI18n: 'temperature.humidity',
    lastUpdated: 'temperature.lastUpdated',
    latestEntry: <Text id="temperature.latestEntry" fields={{ name }} />,
    loading: 'loading',
    temp: 'temperature.temperature',
    temp2: 'temperature.temperature2',
    tempConfig: `temperature.config.${temperatureConfig}`,
    temp2Config: `temperature.config.${temperature2Config}`,
  });

  const formatNumber = (
    number: number,
    options: Intl.NumberFormatOptions = {}
  ): string =>
    new Intl.NumberFormat(locale, {
      maximumFractionDigits: 2,
      minimumFractionDigits: 2,
      ...options,
    }).format(number);

  const ActivityIcon = dynamic(() => import('assets/icons/activity.svg'));

  return (
    <Card variant={variant}>
      {name && (
        <article className={classnames(styles.container, styles.header)}>
          <span role="heading" aria-level={2} aria-label={latestEntry}>
            <strong>{name}</strong>
          </span>
          {link && (
            <Link href={'/stations/' + encodeURIComponent(id)}>
              <a className={styles.link}>
                <ArrowUpRightIcon />
              </a>
            </Link>
          )}
        </article>
      )}
      {temperature && (
        <article className={styles.container}>
          <small role="heading" aria-level={3} className={styles.label}>
            {temp} ({tempConfig}):
          </small>
          <span className={styles.data}>
            {formatNumber(temperature)}
            <sup>°C</sup>
          </span>
        </article>
      )}
      {temperature2 && (
        <>
          <article className={styles.container}>
            <small role="heading" aria-level={3} className={styles.label}>
              {temp2} ({temp2Config}):
            </small>
            <span className={styles.data}>
              {formatNumber(temperature2)}
              <sup>°C</sup>
            </span>
          </article>
          <article className={styles.container}>
            <small role="heading" aria-level={3} className={styles.label}>
              {feelsI18n}:
            </small>
            <span className={styles.data}>
              {formatNumber(feels)}
              <sup>°C</sup>
            </span>
          </article>
          <article className={styles.container}>
            <small role="heading" aria-level={3} className={styles.label}>
              {humidityI18n}:
            </small>
            <span className={styles.data}>
              {formatNumber(humidity, {
                minimumFractionDigits: 0,
                maximumFractionDigits: 0,
              })}
              <sup>%</sup>
            </span>
          </article>
        </>
      )}
      {timestamp && (
        <div className={classnames(styles.container, styles.footer)}>
          <small>
            {lastUpdated}: {dayjs(timestamp).fromNow()}
            {new Date(timestamp).valueOf() < Date.now() - DAY && <AlertIcon />}
          </small>
        </div>
      )}
      {loading && (
        <div className={styles.svgContainer}>
          <ActivityIcon aria-label={loadingLabel} />
        </div>
      )}
    </Card>
  );
};

export default TemperatureCard;
